module.exports = {
  a: require('brittanica-a'),
  b: require('brittanica-b'),
  c: require('brittanica-c'),
  d: require('brittanica-d'),
  e: require('brittanica-e'),
  f: require('brittanica-f'),
  g: require('brittanica-g'),
  h: require('brittanica-h'),
  i: require('brittanica-i'),
  j: require('brittanica-j'),
  k: require('brittanica-k'),
  l: require('brittanica-l'),
  m: require('brittanica-m'),
  n: require('brittanica-n'),
  o: require('brittanica-o'),
  p: require('brittanica-p'),
  q: require('brittanica-q'),
  r: require('brittanica-r'),
  s: require('brittanica-s'),
  t: require('brittanica-t'),
  u: require('brittanica-u'),
  v: require('brittanica-v'),
  w: require('brittanica-w'),
  x: require('brittanica-x'),
  y: require('brittanica-y'),
  z: require('brittanica-z')
}
